name: Unit Tests - iOS

on: push

jobs:
  unit-test-app:
    name: Unit Test App
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-   

      - name: Build and Test
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'app_unit_test'
          bundle-install-path: 'vendor'
